// === DHL track_shipment — looks up a real curated shipment database ===
// Reads the agent input robustly (n8n Code Tool passes value as `query`)
let q = '';
try { if (typeof query !== 'undefined' && query !== null) q = (typeof query === 'string') ? query : JSON.stringify(query); } catch (e) {}
if (!q) { try { if ($json && $json.query) q = String($json.query); } catch (e) {} }
if (!q) { try { q = $fromAI('tracking_number', 'The DHL tracking number'); } catch (e) {} }
const t = String(q || '').replace(/[^0-9]/g, '');
if (!t) return JSON.stringify({ found: false, message: 'Please share your DHL tracking number so I can look it up.' });

// ===== DHL SHIPMENT DATABASE (curated demo data) =====
const DB = {
  '1234567890': { status: 'WITH DELIVERY COURIER', scan: 'Out for delivery', loc: 'Chennai Gateway, Tamil Nadu', eta: 'today by 8 PM', svc: 'DHL Express Worldwide', from: 'Mumbai', to: 'Chennai', wt: '2.3 kg', contents: 'Electronics', customer: 'Arjun Mehta', last: 'picked up by courier at 8:30 AM' },
  '9876543210': { status: 'DELIVERED', scan: 'Delivered and signed for', loc: 'Andheri East, Mumbai', eta: 'delivered June 8 at 2:45 PM', svc: 'DHL eCommerce', from: 'New Delhi', to: 'Mumbai', wt: '0.8 kg', contents: 'Books', customer: 'Priya Sharma', signed: 'P. Sharma', last: 'signed by P. Sharma at 2:45 PM' },
  '1111222233': { status: 'CUSTOMS STATUS UPDATED', scan: 'Held at customs', loc: 'Delhi Customs, IGI Airport', eta: '2 to 3 working days after clearance', svc: 'DHL Express Worldwide', from: 'Frankfurt, DE', to: 'New Delhi', wt: '5.1 kg', contents: 'Machine parts', customer: 'Rakesh Industries', incoterm: 'DAP (receiver pays duty)', last: 'held for commercial invoice at 9 AM' },
  '5555666677': { status: 'SHIPMENT ON HOLD', scan: 'Delayed due to weather', loc: 'Bengaluru Gateway, Karnataka', eta: 'revised to June 12', svc: 'DHL Express Worldwide', from: 'Hyderabad', to: 'Coimbatore', wt: '1.4 kg', contents: 'Garments', customer: 'Lakshmi Textiles', last: 'weather advisory hold at 4 PM' },
  '2222333344': { status: 'IN TRANSIT', scan: 'In transit', loc: 'Mumbai Gateway', eta: 'June 11 by 6 PM', svc: 'DHL Express Worldwide', from: 'Pune', to: 'Bengaluru', wt: '3.2 kg', contents: 'Auto spares', customer: 'TorqueAuto Pvt Ltd', last: 'departed Mumbai Gateway at 11:20 PM' },
  '3333444455': { status: 'SHIPMENT PICKED UP', scan: 'Collection booked', loc: 'Hyderabad (origin)', eta: 'estimated June 13 to 14', svc: 'DHL Express Worldwide', from: 'Hyderabad', to: 'Chennai', wt: '0.5 kg', contents: 'Documents', customer: 'Vikram Rao', last: 'pickup booked for 2 to 6 PM' },
  '4045128890': { status: 'IN TRANSIT', scan: 'Departed facility', loc: 'New Delhi Hub', eta: 'June 12 by 5 PM', svc: 'DHL Express', from: 'Jaipur', to: 'Lucknow', wt: '1.1 kg', contents: 'Handicrafts', customer: 'Rajasthan Crafts', last: 'departed New Delhi Hub' },
  '4045128891': { status: 'DELIVERED', scan: 'Delivered and signed for', loc: 'Salt Lake, Kolkata', eta: 'delivered June 7 at 11:10 AM', svc: 'DHL eCommerce', from: 'Chennai', to: 'Kolkata', wt: '2.0 kg', contents: 'Footwear', customer: 'Ananya Das', signed: 'A. Das', last: 'signed by A. Das' },
  '4045128892': { status: 'WITH DELIVERY COURIER', scan: 'Out for delivery', loc: 'Banjara Hills, Hyderabad', eta: 'today by 7 PM', svc: 'DHL Express', from: 'Bengaluru', to: 'Hyderabad', wt: '0.9 kg', contents: 'Cosmetics', customer: 'Sneha Reddy', last: 'with courier since 10 AM' },
  '4045128893': { status: 'CUSTOMS STATUS UPDATED', scan: 'Clearing customs', loc: 'Mumbai Customs, Sahar', eta: '2 to 4 working days', svc: 'DHL Express Worldwide', from: 'Shanghai, CN', to: 'Mumbai', wt: '12.4 kg', contents: 'LED panels', customer: 'BrightTech', incoterm: 'DAP (receiver pays duty)', last: 'awaiting import duty payment' },
  '4045128894': { status: 'ARRIVED AT FACILITY', scan: 'Arrived at sorting facility', loc: 'Ahmedabad Hub', eta: 'June 13 by 6 PM', svc: 'DHL Express', from: 'Surat', to: 'Indore', wt: '4.7 kg', contents: 'Textile rolls', customer: 'Surat Mills', last: 'arrived Ahmedabad Hub overnight' },
  '4045128895': { status: 'IN TRANSIT', scan: 'In transit', loc: 'Frankfurt Gateway, DE', eta: 'June 15 (international)', svc: 'DHL Express Worldwide', from: 'Bengaluru', to: 'Berlin, DE', wt: '1.8 kg', contents: 'Software dongles', customer: 'CodeWorks GmbH', incoterm: 'DDP (sender pays duty)', last: 'departed Frankfurt Gateway' },
  '4045128896': { status: 'DELIVERED', scan: 'Delivered and signed for', loc: 'Koramangala, Bengaluru', eta: 'delivered June 6 at 4:20 PM', svc: 'DHL Express', from: 'Pune', to: 'Bengaluru', wt: '0.6 kg', contents: 'Mobile accessories', customer: 'Karthik Nair', signed: 'K. Nair', last: 'signed by K. Nair' },
  '4045128897': { status: 'SHIPMENT ON HOLD', scan: 'Address clarification needed', loc: 'Chennai Hub', eta: 'pending address confirmation', svc: 'DHL eCommerce', from: 'Kochi', to: 'Chennai', wt: '1.3 kg', contents: 'Spices', customer: 'Kerala Spice Co', last: 'held — incomplete delivery address' },
  '4045128898': { status: 'WITH DELIVERY COURIER', scan: 'Out for delivery', loc: 'Vashi, Navi Mumbai', eta: 'today by 9 PM', svc: 'DHL Express', from: 'Nagpur', to: 'Navi Mumbai', wt: '5.5 kg', contents: 'Industrial tools', customer: 'MetalEdge', last: 'on delivery vehicle MH-43' },
  '4045128899': { status: 'IN TRANSIT', scan: 'In transit', loc: 'Dubai Hub, AE', eta: 'June 14 (international)', svc: 'DHL Express Worldwide', from: 'Chennai', to: 'Dubai, AE', wt: '2.9 kg', contents: 'Jewellery samples', customer: 'GoldLine Exports', incoterm: 'DDP (sender pays duty)', last: 'transit via Dubai Hub' },
  '7001234561': { status: 'DELIVERED', scan: 'Delivered and signed for', loc: 'Gomti Nagar, Lucknow', eta: 'delivered June 5 at 1:15 PM', svc: 'DHL eCommerce', from: 'Delhi', to: 'Lucknow', wt: '1.0 kg', contents: 'Stationery', customer: 'Ravi Verma', signed: 'R. Verma', last: 'signed by R. Verma' },
  '7001234562': { status: 'WITH DELIVERY COURIER', scan: 'Out for delivery', loc: 'Aundh, Pune', eta: 'today by 6 PM', svc: 'DHL Express', from: 'Mumbai', to: 'Pune', wt: '0.7 kg', contents: 'Pharma samples', customer: 'MediCare Labs', last: 'out for delivery since 9:30 AM' },
  '7001234563': { status: 'CUSTOMS STATUS UPDATED', scan: 'Held at customs', loc: 'Bengaluru Customs', eta: '3 working days after clearance', svc: 'DHL Express Worldwide', from: 'Singapore, SG', to: 'Bengaluru', wt: '8.2 kg', contents: 'Lab equipment', customer: 'BioGen Research', incoterm: 'DAP (receiver pays duty)', last: 'KYC document requested' },
  '7001234564': { status: 'IN TRANSIT', scan: 'In transit', loc: 'Kolkata Gateway', eta: 'June 12 by 8 PM', svc: 'DHL Express', from: 'Guwahati', to: 'Kolkata', wt: '3.8 kg', contents: 'Tea consignment', customer: 'Assam Tea Estates', last: 'departed Guwahati facility' },
  '7001234565': { status: 'ARRIVED AT FACILITY', scan: 'Arrived at sorting facility', loc: 'New Delhi Hub', eta: 'June 13 by 4 PM', svc: 'DHL Express', from: 'Chandigarh', to: 'Agra', wt: '2.1 kg', contents: 'Leather goods', customer: 'Punjab Leatherworks', last: 'arrived New Delhi Hub' },
  '7001234566': { status: 'DELIVERED', scan: 'Delivered and signed for', loc: 'T. Nagar, Chennai', eta: 'delivered June 4 at 10:05 AM', svc: 'DHL Express', from: 'Bengaluru', to: 'Chennai', wt: '1.5 kg', contents: 'Silk sarees', customer: 'Meena Krishnan', signed: 'M. Krishnan', last: 'signed by M. Krishnan' },
  '7001234567': { status: 'SHIPMENT ON HOLD', scan: 'Delayed — high volume', loc: 'Mumbai Gateway', eta: 'revised to June 13', svc: 'DHL eCommerce', from: 'Ahmedabad', to: 'Mumbai', wt: '0.4 kg', contents: 'SIM cards', customer: 'ConnectTel', last: 'held — festival season backlog' },
  '7001234568': { status: 'WITH DELIVERY COURIER', scan: 'Out for delivery', loc: 'Civil Lines, Jaipur', eta: 'today by 7:30 PM', svc: 'DHL Express', from: 'Delhi', to: 'Jaipur', wt: '6.0 kg', contents: 'Marble samples', customer: 'Rajasthan Marbles', last: 'on vehicle RJ-14' },
  '7001234569': { status: 'IN TRANSIT', scan: 'In transit', loc: 'London Heathrow, UK', eta: 'June 16 (international)', svc: 'DHL Express Worldwide', from: 'Mumbai', to: 'London, UK', wt: '4.2 kg', contents: 'Pharma export', customer: 'Cipla Exports', incoterm: 'DDP (sender pays duty)', last: 'cleared London Heathrow' },
  '8009988771': { status: 'DELIVERED', scan: 'Delivered to neighbour', loc: 'HSR Layout, Bengaluru', eta: 'delivered June 3 at 5:40 PM', svc: 'DHL eCommerce', from: 'Hyderabad', to: 'Bengaluru', wt: '0.9 kg', contents: 'Headphones', customer: 'Aditya Menon', signed: 'neighbour, Flat 4B', last: 'left with neighbour, Flat 4B' },
  '8009988772': { status: 'CUSTOMS STATUS UPDATED', scan: 'Clearing customs', loc: 'Delhi Customs, IGI Airport', eta: '2 to 3 working days', svc: 'DHL Express Worldwide', from: 'New York, US', to: 'New Delhi', wt: '3.3 kg', contents: 'Medical device', customer: 'HealthFirst', incoterm: 'DAP (receiver pays duty)', last: 'duty assessment in progress' },
  '8009988773': { status: 'WITH DELIVERY COURIER', scan: 'Out for delivery', loc: 'Anna Nagar, Chennai', eta: 'today by 8 PM', svc: 'DHL Express', from: 'Madurai', to: 'Chennai', wt: '1.7 kg', contents: 'Temple artefacts', customer: 'Heritage Crafts', last: 'with courier TN-09' },
  '8009988774': { status: 'IN TRANSIT', scan: 'In transit', loc: 'Nagpur Hub', eta: 'June 12 by 7 PM', svc: 'DHL Express', from: 'Raipur', to: 'Mumbai', wt: '9.1 kg', contents: 'Steel fittings', customer: 'IronWorks Ltd', last: 'departed Nagpur Hub' },
  '8009988775': { status: 'DELIVERED', scan: 'Delivered and signed for', loc: 'Vasant Kunj, New Delhi', eta: 'delivered June 2 at 12:30 PM', svc: 'DHL Express', from: 'Mumbai', to: 'New Delhi', wt: '0.3 kg', contents: 'Legal documents', customer: 'Sharma & Associates', signed: 'office reception', last: 'signed at office reception' },
  '8009988776': { status: 'SHIPMENT PICKED UP', scan: 'Collection booked', loc: 'Kochi (origin)', eta: 'estimated June 14 to 15', svc: 'DHL Express Worldwide', from: 'Kochi', to: 'Dubai, AE', wt: '2.6 kg', contents: 'Cashew export', customer: 'Kerala Cashews', incoterm: 'DDP (sender pays duty)', last: 'pickup scheduled today' }
};

const r = DB[t];
if (!r) {
  return JSON.stringify({ found: false, tracking_number: t, message: 'No shipment found for that number in our system. Please verify the tracking number from your DHL shipping confirmation — DHL Express waybills are 10 digits.' });
}
const o = { found: true, tracking_number: t, status: r.status, latest_scan: r.scan, current_location: r.loc, estimated_delivery: r.eta, service: r.svc, origin: r.from, destination: r.to, weight: r.wt, contents: r.contents, customer: r.customer, last_event: r.last };
if (r.incoterm) o.incoterm = r.incoterm;
if (r.status === 'DELIVERED') o.pod_available = true;
return JSON.stringify(o);
